language: python

matrix:
  include:
  - python: "3.4"
    env: TOX_ENV=py34
  - python: "3.5"
    env: TOX_ENV=py35
  - python: "3.5"
    env: TOX_ENV=pep8

install:
  - pip install tox-travis

script: tox -e $TOX_ENV
